### PR TITLE
More correct RFC-5321 Mailbox syntax check

### PR DESCRIPTION
**Pull request by gene-hightower**
Switch from isemail package to smtp-address-parser for more correct RFC-5321 / RFC-6531 Mailbox address syntax check.

### CODE REVIEW

**Comment by carlo-quinonez** [comment]
I had no idea spaces were allowed characters in email addresses. Is there a reference somewhere you can point to?

**Comment by gene-hightower** [comment]
Yes, the primary reference is RFC-5321 section 4.1.2.  Command Argument Syntax <https://tools.ietf.org/html/rfc5321#section-4.1.2>
The rule for Mailbox Local-part allows Quoted-string which can, inside the quotes, contain "any ASCII graphic or space" [...] "except double-quote and the backslash itself."

**Comment by gene-hightower** [comment]
BTW: I opened an issue with the isemail project with more or less this same example, perhaps they can correct their code.
<https://github.com/skeggse/isemail/issues/213#issue-833400894>

However, I don't think their intent is to check for strict adherence to RFC-5321, rather "validate an email address according to RFCs 5321, 5322, and others" as they state. Including the phrase "for various definitions thereof" in their documentation.

The JSON schema validation spec here:
<https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.7.3.2>
Refers to RFC-5321 as the basis for validation.

**Comment by carlo-quinonez** [comment]
Interesting. I saw you used `nearley` to create `smtp-address-parser` - I've been curious about `nearley` for awhile. I'm tempted to merge this just because of that!

So how do you think test coverage for `smtp-address-parser` compares to `isemail`? I took a quick glance at the tests and noticed there's no check for valid tld...

**Comment by gene-hightower** [comment]
Test coverage should be improved, for sure. I'm happy to accept suggestions for tests. Or better yet, PRs.

As for valid TLDs, I think that's a test you need DNS for. My understanding is that schema validation is about checking the *form* of the address (it's syntax) but not, for example, checking actual deliverability of the address. For example, there is no check for an MX (Mail eXchange) record for the domain.

The list of valid TLDs has expanded recently to include a bunch of new ones.

My confidence in the correctness of the parser has to do with it's rule-based construction. The rules used in the parser have close to a 1-to-1 correspondence to those in the grammar of the RFC. Of course, tests are never a bad thing.

**Comment by carlo-quinonez** [comment]
Good points.

**Pull request merged**
